# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: David McWee
email: dmcwee@microsoft.com
description: >- # this means to ignore newlines until "baseurl:"
  Security that works together, Works.  
baseurl: "" # the subpath of your site, e.g. /blog
domain: "davidmcwee.com"
url: "https://davidmcwee.com" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: "G-K5M43KBSNX"
excerpt_separator: <!--more-->
bs-theme: "light"
nav-bs-theme: "dark"
image: /assets/images/me.png

# Build settings
markdown: kramdown
highlighter: rouge
show_excerpts: true
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed

defaults:
- 
  scope:
    path: ""
  values:
    layout: "default"
    author: "David McWee"
    seo_type: "Site"
- 
  scope:
    path: "_posts"
  values:
    type: "posts"
    layout: "post"
    twitter_summary: true
    seo_type: "BlogPosting"
    theme: light

collections:
  labs:
    output: true
  projects:
    output: true
  archive:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

include:
- .well-known

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
#exclude:
#- categories
#  - _posts/drafts
#  - _posts/archive
#  - *.draft.*
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/